config/routes.rb
PcrCloning::Application.routes.draw do

  namespace :public do
    get "pcr_cloning_requests/new"
    post "pcr_cloning_requests/create"
    get "pcr_cloning_requests/sent"
    get "pdf_req_download/:folio" => 'pcr_cloning_requests#pdf_req_download', as: 'pdf_req_download'
  end

  namespace :requests do
    resources :states
  end

  namespace :requests do
    resources :clonings
    get 'clonings/delete/:id' => 'clonings#delete', as: 'cloning_delete'
    post 'download_xlsx' => 'clonings#download_xlsx', as: 'clonning_download_xlsx'
    get 'xlsx_range' => 'clonings#xlsx_range', as: 'cloning_xlsx_range'
    get "pdf_req_download/:folio" => 'clonings#pdf_req_download', as: 'pdf_req_download'
  end

  devise_for :devise_users
  namespace :admin do
    resources :users
    get 'users/delete/:id' => 'users#delete', as: 'delete_user'

    get 'system_config' => 'system_configs#index'
    post 'system_config/update' => 'system_configs#update'
  end

  root 'requests/clonings#index'

end

app/models/admin/system_config.rb
class Admin::SystemConfig

  require 'yaml'

  class << self
    attr_accessor :internal_price, :external_price, :new_request_mails, :new_deposit_slip_mail

    def get
      config = YAML.load_file('config/system_config.yml')
      self.internal_price = config['prices']['internal']
      self.external_price = config['prices']['external'] 
      self.new_request_mails = config['notifications']['new_request_mails']
      self.new_deposit_slip_mail = config['notifications']['new_deposit_slip_mail']
    end

   def update(params)
      config = YAML.load_file('config/system_config.yml')
      config['prices']['internal'] = params[:internal_price].to_i if params[:internal_price]
      config['prices']['external'] = params[:external_price].to_i if params[:external_price]
      config['notifications']['new_request_mails'] = params[:new_request_mails] if params[:new_request_mails] 
      config['notifications']['new_deposit_slip_mail'] = params[:new_deposit_slip_mail] if params[:new_deposit_slip_mail] 
      File.open('config/system_config.yml','w') {|f| f.write config.to_yaml}
   end
  end

end

app/controllers/admin/system_configs_controller.rb
class Admin::SystemConfigsController < ApplicationController
  before_action :set_admin_system_config, only: [:index]

  def index
  end

  def update
    Admin::SystemConfig.update(params)
    #TODO translate notice
    redirect_to admin_system_config_path, notice: 'Configuración actualizada correctamente'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_system_config
      Admin::SystemConfig.get
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_system_config_params
      params[:admin_system_config]
    end
end

app/helpers/admin/system_configs_helper.rb
module Admin::SystemConfigsHelper
end

app/views/admin/system_configs/_form.html.haml
= form_for @admin_system_config do |f|
  - if @admin_system_config.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_system_config.errors.count, "error")} prohibited this admin_system_config from being saved:"
      %ul
        - @admin_system_config.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/system_configs/edit.html.haml
%h1 Editing admin_system_config

= render 'form'

= link_to 'Show', @admin_system_config
\|
= link_to 'Back', admin_system_configs_path

app/views/admin/system_configs/index.html.haml
#menu
  =render partial: 'layouts/admin_menu'

%h1= t('titles.system_config')
.sp


.alert-notice
  =render partial: 'layouts/alert_notice'
  .sp 

= form_tag admin_system_config_update_path, method: 'post' do
  .tbl-system-config
    %strong.col-1.t-right
      -#TODO Traducir etiquetas
      Precio al público
    .col-2
      = text_field_tag :internal_price, Admin::SystemConfig.internal_price
    %strong.col-1.t-right
      Precio interno 
    .col-2
      = text_field_tag :external_price, Admin::SystemConfig.external_price
    %strong.col-1.t-right
      Correos para notificar nuevas solicitudes
    .col-2
      = text_field_tag :new_request_mails, Admin::SystemConfig.new_request_mails, size: 70
    %strong.col-1.t-right
      Correos para solicitar ficha de depósito
    .col-2
      = text_field_tag :new_deposit_slip_mail, Admin::SystemConfig.new_deposit_slip_mail, size: 40
  .sp   
  = jq_submit_tag t('commands.save') 
  

app/views/admin/system_configs/new.html.haml
%h1 New admin_system_config

= render 'form'

= link_to 'Back', admin_system_configs_path

app/views/admin/system_configs/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_system_config_path(@admin_system_config)
\|
= link_to 'Back', admin_system_configs_path