config/routes.rb
PcrCloning::Application.routes.draw do

  namespace :public do
    get "pcr_cloning_requests/new"
    post "pcr_cloning_requests/create"
    get "pcr_cloning_requests/sent"
    get "pdf_req_download/:folio" => 'pcr_cloning_requests#pdf_req_download', as: 'pdf_req_download'
  end

  namespace :requests do
    resources :states
  end

  namespace :requests do
    resources :clonings
    get 'clonings/delete/:id' => 'clonings#delete', as: 'cloning_delete'
    post 'download_xlsx' => 'clonings#download_xlsx', as: 'clonning_download_xlsx'
    get 'xlsx_range' => 'clonings#xlsx_range', as: 'cloning_xlsx_range'
    get "pdf_req_download/:folio" => 'clonings#pdf_req_download', as: 'pdf_req_download'
  end

  devise_for :devise_users
  namespace :admin do
    resources :users
    get 'users/delete/:id' => 'users#delete', as: 'delete_user'

    get 'system_config' => 'system_configs#index'
    post 'system_config/update' => 'system_configs#update'
  end

  root 'requests/clonings#index'

end

app/models/requests.rb
module Requests
  def self.table_name_prefix
    'requests_'
  end
end

app/models/requests/cloning.rb
# -*- coding: utf-8 -*-
class Requests::Cloning < ActiveRecord::Base
  belongs_to :state, :class_name => 'Requests::State', :foreign_key => :inv_state_id
  validates :name, :company, :mail,
            :sample_name, :sample_volume, :pcr_product_size, :group_leader, :payment_method, :req_type, presence: true

  before_validation :set_price
  before_create :set_folio

  def set_folio
    self.folio = Time.now
  end

  def set_price
    Admin::SystemConfig.get
    if self.payment_method < 4
      self.price = Admin::SystemConfig.internal_price
    else
      self.price = Admin::SystemConfig.external_price
    end
  end

  #TODO remove if possible
  attr_accessor :start_date, :end_date

  def self.search(search)
    if search
      where("(translate(lower(name),'áéíóúàèìòù', 'aeiouaeiou') LIKE translate(lower(?),'áéíóúàèìòù', 'aeiouaeiou')\
            OR translate(lower(sample_name),'áéíóúàèìòù', 'aeiouaeiou') LIKE translate(lower(?),'áéíóúàèìòù', 'aeiouaeiou'))",
            "%#{search}%","%#{search}%")
    else
      all
    end
  end

   PMT_METHOD = {
      1 => 'UR',
      2 => 'Conacyt',
      3 => 'PAPIIT',
      4 => 'Efectivo',
      5 => 'Depósito bancario'
   }

   TYPE ={
       1 => 'Clonación Sencilla',
       2 => 'Clonación y Secuenciación'
   }

   SEQ_TYPE ={
       1 => 'Forward',
       2 => 'Reverse',
       3 => 'Ambos'
   }

end

app/models/requests/state.rb
class Requests::State < ActiveRecord::Base
end

app/controllers/requests/clonings_controller.rb
class Requests::CloningsController < ApplicationController

  require 'pdf_generator'
  require 'xlsx_generator'

  before_action :set_requests_cloning, only: [:show, :edit, :update, :destroy, :delete]
  helper_method :sort_column, :sort_direction

  # GET /requests/clonings
  # GET /requests/clonings.json
  def index
    @requests_clonings = Requests::Cloning.search(params[:search]).order("#{sort_column} #{sort_direction}").paginate(per_page: 15, page:  params[:page])
  end

  # GET /requests/clonings/1
  # GET /requests/clonings/1.json
  def show
  end

  # GET /requests/clonings/new
  def new
    @requests_cloning = Requests::Cloning.new
  end

  # GET /requests/clonings/1/edit
  def edit
  end

  # POST /requests/clonings
  # POST /requests/clonings.json
  def create
    @requests_cloning = Requests::Cloning.new(requests_cloning_params)

    respond_to do |format|
      if @requests_cloning.save
        #Generarte PDF
        filename = "public/pdf/#{'%.6d' % @requests_cloning.id}_pcr.pdf"
        PdfGenerator.request(@requests_cloning, filename)
        format.html { redirect_to @requests_cloning, notice: t('notices.saved_successfully') }
        format.json { render action: 'show',
                             status: :created, location: @requests_cloning }



      else
        format.html { render action: 'new' }
        format.json { render json: @requests_cloning.errors,
                             status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /requests/clonings/1
  # PATCH/PUT /requests/clonings/1.json
  def update
#    @requests_cloning = Requests::Cloning.find(params[:id])

    respond_to do |format|
      if @requests_cloning.update(requests_cloning_params)
        #Generarte PDF
        filename = "public/pdf/#{'%.6d' % @requests_cloning.id}_pcr.pdf"
        PdfGenerator.request(@requests_cloning, filename)
        format.html { redirect_to @requests_cloning, notice: t('notices.updated_successfully') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @requests_cloning.errors, status: :unprocessable_entity }
      end
    end

  end


  def delete

  end

  # DELETE /requests/clonings/1
  # DELETE /requests/clonings/1.json
  def destroy
    @requests_cloning.destroy
    index
  end

  def pdf_req_download
    @requests_cloning = Requests::Cloning.find_by_folio(params[:folio])
    filename= "#{'%.6d' % @requests_cloning.id}_pcr.pdf"
    file = "public/pdf/#{filename}"
    send_file  file, filename: filename, type: "application/pdf"
  end

  def xlsx_range
    #@requests_cloning = Requests::Cloning.find(1)
  end


  def download_xlsx
    start_date = params['date_range']['start_date'].to_date
    end_date = params['date_range']['end_date'].to_date
    select = "folio, created_at, sample_name, sample_volume, pcr_product_size, req_type,\
              sequencing_type, name, company, mail, phone, shipping_address, group_leader,\
              payment_method, inv_name, inv_rfc, inv_address, inv_state_id, inv_municipality, inv_mail, price"
    requests_cloning = Requests::Cloning.select(select).where(:created_at => start_date.beginning_of_day..end_date.end_of_day)
    XlsxGenerator.generate_xlsx(requests_cloning, start_date, end_date, select)
    send_file("#{Rails.root}/public/xlsx/pcr_clonings_requests.xlsx", filename: "clonings_#{Time.now().strftime('%Y%M%d%H%m')}.xlsx", type: "application/vnd.ms-excel")
  end

=begin
  def generate_xlsx(requests, start_date, end_date, columns)
    package = Axlsx::Package.new
    workbook = package.workbook

    workbook.add_worksheet(name: "Clonaciones") do |sheet|
      title = sheet.styles.add_style sz: 16, b: 1
      headers = sheet.styles.add_style sz: 12, alignment: { horizontal: :left }, b: 1, fg_color: '000000', bg_color: "dee1e3"

      # Course name and start date
      sheet.add_row ["#{t("titles.requests_clonings")} (#{start_date} -  #{end_date})"], :style => title, :widths=>[6]
      sheet.add_row

      # Records header
      values = ['No.']
      columns.split(',').each do |c|
        values << I18n.t("activerecord.attributes.requests/cloning.#{c.strip}")
      end
      #requests cloning Headers
      #requests.column_names.each do |f|
      #  case f
      #    when "id"
      #    when "created_at"
      #    when "updated_at"
      #    else
      #     values << I18n.t("activerecord.attributes.requests/cloning.#{f.to_s}")
      #  end
      #end
      sheet.add_row values, :style => headers

      #Cloning requests - Detail
      values = nil
      requests.each_with_index  do |r,i|
        values = [i+1]
        r.attributes.each do |f|
          case f[0]
            when "req_type"
              values<< Requests::Cloning::TYPE[f[1]]
            when "sequencing_type"
              values << Requests::Cloning::SEQ_TYPE[f[1]]
            when 'payment_method'
              values << Requests::Cloning::PMT_METHOD[f[1]]
            when 'inv_state_id'
              values << r.state.name
            else
              values << f[1]
          end
        end
        sheet.add_row values
      end

     end # end workbook

    package.serialize("public/xlsx/pcr_clonings_requests.xlsx")
  end
=end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requests_cloning
      @requests_cloning = Requests::Cloning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requests_cloning_params
      params.require(:requests_cloning).permit(:name, :company, :mail, :phone, :shipping_address, :group_leader,
                                               :payment_method, :sample_name, :sample_volume, :pcr_product_size,
                                               :req_type, :sequencing_type, :inv_name, :inv_rfc, :inv_address, :inv_city,
                                               :inv_municipality, :inv_state_id, :inv_mail)
    end

  def sort_column
    params[:sort] || 'created_at'
  end

  def sort_direction
    params[:direction] || 'asc'
  end

end

app/controllers/requests/states_controller.rb
class Requests::StatesController < ApplicationController
  before_action :set_requests_state, only: [:show, :edit, :update, :destroy]

  # GET /requests/states
  # GET /requests/states.json
  def index
    @requests_states = Requests::State.all
  end

  # GET /requests/states/1
  # GET /requests/states/1.json
  def show
  end

  # GET /requests/states/new
  def new
    @requests_state = Requests::State.new
  end

  # GET /requests/states/1/edit
  def edit
  end

  # POST /requests/states
  # POST /requests/states.json
  def create
    @requests_state = Requests::State.new(requests_state_params)

    respond_to do |format|
      if @requests_state.save
        format.html { redirect_to @requests_state, notice: 'State was successfully created.' }
        format.json { render action: 'show', status: :created, location: @requests_state }
      else
        format.html { render action: 'new' }
        format.json { render json: @requests_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/states/1
  # PATCH/PUT /requests/states/1.json
  def update
    respond_to do |format|
      if @requests_state.update(requests_state_params)
        format.html { redirect_to @requests_state, notice: 'State was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @requests_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/states/1
  # DELETE /requests/states/1.json
  def destroy
    @requests_state.destroy
    respond_to do |format|
      format.html { redirect_to requests_states_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requests_state
      @requests_state = Requests::State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requests_state_params
      params.require(:requests_state).permit(:name)
    end
end

app/helpers/requests/clonings_helper.rb
module Requests::CloningsHelper
end

app/helpers/requests/states_helper.rb
module Requests::StatesHelper
end

app/views/requests/clonings/_commands_for_form.html.haml
.t-right
  =submit_tag_fa_button t('commands.save')
  =link_to_fa_button({url: requests_clonings_path, text: t('commands.cancel'), icon: 'fa-times', remote: false})

app/views/requests/clonings/_form.html.haml
= render partial: 'layouts/validation_errors', locals: {errors: @requests_cloning.errors}
.sp
= simple_form_for @requests_cloning, url: url, :html => {:novalidate => true, multipart: true} do |f|

  = render partial: 'commands_for_form'
  %hr

  %h3.t-head= t('titles.user_data')
  .tbl-clonings-attr
    .col-1
      =f.label :name
    .col-2
      =f.input_field :name, :size => 70
    .col-1
      =f.label :company
    .col-2
      =f.input_field :company, :size => 70
    .col-1
      =f.label :mail
    .col-2
      =f.input_field :mail, :size => 70
    .col-1
      =f.label :phone
    .col-2
      =f.input_field :phone, :size => 70
    .col-1
      =f.label :shipping_address
    .col-2
      =f.input_field :shipping_address, :size => 70, placeholder: 'Sólo si requiere que los resultados sean enviados por paquetería (con costo adicional)'
    .col-1
      =f.label :group_leader
    .col-2
      =f.input_field :group_leader, :size => 60

  %h3.t-head= t('titles.sample_data')
  .tbl-clonings-attr
    .col-1
      =f.label :sample_name
    .col-2
      =f.input_field :sample_name, :size => 60
    .col-1
      =f.label :sample_volume
    .col-2
      =f.input_field :sample_volume, :size => 60
    .col-1
      =f.label :pcr_product_size
    .col-2
      =f.input_field :pcr_product_size, :size => 60
    .col-1
      =f.label :req_type
    .col-2
      =f.collection_radio_buttons :req_type, Requests::Cloning::TYPE, :first, :last, checked: @requests_cloning.req_type
    #seq_type
      .col-1
        =f.label :sequencing_type
      .col-2
        =f.collection_radio_buttons :sequencing_type, Requests::Cloning::SEQ_TYPE, :first, :last, checked: @requests_cloning.sequencing_type
  %h3.t-head= t('titles.invoice_data')
  .tbl-clonings-attr
    .col-1
      =f.label :payment_method
    .col-2
      =f.collection_radio_buttons :payment_method, Requests::Cloning::PMT_METHOD, :first, :last, checked: @requests_cloning.payment_method
    .col-1
      =f.label :inv_name
    .col-2
      =f.input_field :inv_name, :size => 60
    .col-1
      =f.label :inv_rfc
    .col-2
      =f.input_field :inv_rfc, :size => 60
    .col-1
      =f.label :inv_address
    .col-2
      =f.input_field :inv_address, :size => 60
    .col-1
      =f.label :inv_municipality
    .col-2
      =f.input_field :inv_municipality, :size => 60
    .col-1
      =f.label :inv_state_id
    .col-2
      =f.select :inv_state_id, options_from_collection_for_select(Requests::State.all, :id, :name, @requests_cloning.inv_state_id),  :size => 70
    .col-1
      =f.label :inv_mail
    .col-2
      =f.input_field :inv_mail, :size => 60
  .sp
  %hr

  = render partial: 'commands_for_form'
  .sp

app/views/requests/clonings/_record_tbl.html.haml
.tbl-clonings.t-head
  .col-1
    =sortable 'name', t('titles.name'), requests_clonings_path
  .col-2
    =sortable 'sample_name', t('titles.sample_name'), requests_clonings_path
  .col-3
    &nbsp

-# @requests_clonings.each_with_index do |requests_cloning, i|
- i=0
- @requests_clonings.each do |requests_cloning|
  - i += 1
  .tbl-clonings{:id => "row-#{i}",:class => "alt-#{i % 2}" }
    .col-1
      = requests_cloning.name
    .col-2
      = requests_cloning.sample_name
    .col-3.t-cent
      = link_to_fa_button({url: requests_cloning, icon: 'fa-eye', title: t('commands.show'), remote: false})
      = link_to_fa_button({url: edit_requests_cloning_path(requests_cloning), icon: 'fa-pencil', title: t('commands.edit'), remote: false})
      = link_to_fa_button({url: requests_cloning_delete_path(requests_cloning), icon: 'fa-trash-o', title: 'Eliminar'})
      = link_to_fa_button({url: requests_pdf_req_download_path(requests_cloning.folio), icon: 'fa-file-pdf-o', title: t('commands.download', param: t('titles.pdf_request')), remote: false})

      -#= link_to_jq_button({url: admin_delete_user_path(admin_user), icon: 'trash', title: 'Eliminar'})

app/views/requests/clonings/_xlsx_range.html.haml
.error-explanation
= simple_form_for :date_range, url: requests_clonning_download_xlsx_path,  :html => {multipart: true}  do |f|
  De
  = f.input_field :start_date, class: 'jq-datepicker', value: Date.today.beginning_of_month.strftime('%Y/%m/%d'), autofocus: false
  a
  = f.input_field :end_date, class: 'jq-datepicker', value: Date.today.strftime('%Y/%m/%d'), autofocus: true
  .sp
  %hr
  .t-right
    = submit_tag_fa_button t('commands.download', param: t('titles.xlsx_file'), )

app/views/requests/clonings/create.js.haml
-#TODO Translate Errors
- if @errors
  $('.error-explanation').html("#{escape_javascript(render 'layouts/validation_errors', errors: @errors)}");
  resize_and_center_ui_dialog();
- else
  :plain
    $('#new-dialog').dialog("close");

app/views/requests/clonings/destroy.js.haml
$('#delete-dialog').dialog('close');
$('#record-list').empty();
$('#record-list').html("#{escape_javascript(render 'record_tbl')}");
jqbuttons();

app/views/requests/clonings/edit.html.haml
%h1= t('titles.edit', param: t('titles.cloning') )

= render partial: 'form', locals: {url: @requests_cloning}


-#= render 'form', url: @requests_cloning, url_cancel: requests_clonings_path

app/views/requests/clonings/index.html.haml
#menu
  =render partial: 'layouts/admin_menu'

%h1= t('titles.requests_clonings')

.alert-notice
  =render partial: 'layouts/alert_notice'


=render 'layouts/search', url: requests_clonings_path

.t-right
  = link_to_fa_button({url: new_requests_cloning_path, text: t('commands.new'), icon: 'fa-plus-square-o',remote: false})
  = link_to_fa_button({url: requests_cloning_xlsx_range_path, text: t('titles.xls_clonings'), icon:'fa-download',remote: true})
%br
#record-list
  =render partial: 'record_tbl'

.sp
.t-right
  = link_to_fa_button({url: new_requests_cloning_path, text: t('commands.new'), icon: 'fa-plus-square-o',remote: false})
  = link_to_fa_button({url: requests_cloning_xlsx_range_path, text: t('titles.xls_clonings'), icon:'fa-download',remote: true})

.sp

#delete-dialog
#xlsx-range

app/views/requests/clonings/index.js.haml
:plain
  if(!$("#new-dialog").is(":empty")){
    $("#new-dialog").dialog("close");
  }
  $('#record-list').empty();
  $('#record-list').html("#{escape_javascript(render 'record_tbl')}");
  remote_will_paginate();
  jqbuttons();

app/views/requests/clonings/new.html.haml
%h1= t('titles.new', param: t('titles.cloning') )

= render partial: 'form', locals: {url: @requests_cloning.id}

-#= link_to 'Back', requests_clonings_path

app/views/requests/clonings/show.html.haml
%h1= t('titles.cloning')

.t-right
  = link_to_fa_button({url: edit_requests_cloning_path(@requests_cloning), text: t('commands.edit'), title: t('commands.edit'), icon: 'fa-pencil', remote: false})
  = link_to_fa_button({url: requests_clonings_path, text: t('commands.close'), icon: 'fa-times', remote: false})
.sp

.alert-notice
  =render partial: 'layouts/alert_notice'

= show_for @requests_cloning do |r|

  %h3.t-head= t('titles.user_data')
  .tbl-clonings-attr
    .col-1
      = r.label :folio
    .col-2
      = r.value :folio
    .col-1
      = r.label :name
    .col-2
      = r.value :name
    .col-1
      = r.label :company
    .col-2
      = r.value :company
    .col-1
      = r.label :mail
    .col-2
      = r.value :mail
    .col-1
      = r.label :phone
    .col-2
      = r.value :phone
    .col-1
      = r.label :shipping_address
    .col-2
      = r.value :shipping_address
    .col-1
      = r.label :group_leader
    .col-2
      = r.value :group_leader

  %h3.t-head= t('titles.sample_data')
  .tbl-clonings-attr
    .col-1
      = r.label :sample_name
    .col-2
      = r.value :sample_name
    .col-1
      = r.label :sample_volume
    .col-2
      = r.value :sample_volume
    .col-1
      = r.label :pcr_product_size
    .col-2
      = r.value :pcr_product_size
    .col-1
      = r.label :req_type
    .col-2
      .wrapper=Requests::Cloning::TYPE[@requests_cloning.req_type]
    .col-1
      = r.label :sequencing_type
    .col-2
      .wrapper=Requests::Cloning::SEQ_TYPE[@requests_cloning.sequencing_type]
  %h3.t-head= t('titles.invoice_data')
  .tbl-clonings-attr
    .col-1
      = r.label :payment_method
    .col-2
      .wrapper=Requests::Cloning::PMT_METHOD[@requests_cloning.payment_method]
    .col-1
      = r.label :inv_name
    .col-2
      = r.value :inv_name
    .col-1
      = r.label :inv_rfc
    .col-2
      = r.value :inv_rfc
    .col-1
      = r.label :inv_address
    .col-2
      = r.value :inv_address
    .col-1
      = r.label :inv_municipality
    .col-2
      = r.value :inv_municipality
    .col-1
      = r.label :inv_state_id
    .col-2
      .wrapper=@requests_cloning.state.name
    .col-1
      = r.label :inv_mail
    .col-2
      = r.value :inv_mail

-#= link_to 'Edit', edit_requests_cloning_path(@requests_cloning)
-#\|
-#= link_to 'Back', requests_clonings_path

app/views/requests/clonings/update.js.haml
- if @errors
  $('.error-explanation').html("#{escape_javascript(render 'layouts/validation_errors', errors: @errors)}");
  center_ui_dialog();
- else
  :plain
    $('#new-dialog').dialog("close");
    $('#show-dialog').html("#{escape_javascript(render 'show')}");
    $('#show-dialog').dialog({modal: true, width: 450});
    $('#record-list').empty();
    $('#record-list').html("#{escape_javascript(render 'record_tbl')}");
    jqbuttons();

app/views/requests/clonings/xlsx_file.js.haml
- if @errors
  $('.error-explanation').html("#{escape_javascript(render 'layouts/validation_errors', errors: @errors)}");
  center_ui_dialog();
- else
  :plain
    $('#xlsx-range').dialog("close");
    jqbuttons();

app/views/requests/clonings/xlsx_range.js.haml
:plain
  $('#xlsx-range').html("#{escape_javascript(render 'xlsx_range')}");
  $('#xlsx-range').dialog({
    title: "#{t("titles.xlsx_range")}",
    width: 480,
    modal: true,
  });
  jqdatepicker();
  -//If focus is in date inputs jquery calendar dosen't appear on click
  $('[name="commit"]').focus();
  $('[name="commit"]').click(function(){
    $('#xlsx-range').dialog('close');
  })