config/routes.rb
PcrCloning::Application.routes.draw do

  namespace :public do
    get "pcr_cloning_requests/new"
    post "pcr_cloning_requests/create"
    get "pcr_cloning_requests/sent"
    get "pdf_req_download/:folio" => 'pcr_cloning_requests#pdf_req_download', as: 'pdf_req_download'
  end

  namespace :requests do
    resources :states
  end

  namespace :requests do
    resources :clonings
    get 'clonings/delete/:id' => 'clonings#delete', as: 'cloning_delete'
    post 'download_xlsx' => 'clonings#download_xlsx', as: 'clonning_download_xlsx'
    get 'xlsx_range' => 'clonings#xlsx_range', as: 'cloning_xlsx_range'
    get "pdf_req_download/:folio" => 'clonings#pdf_req_download', as: 'pdf_req_download'
  end

  devise_for :devise_users
  namespace :admin do
    resources :users
    get 'users/delete/:id' => 'users#delete', as: 'delete_user'

    get 'system_config' => 'system_configs#index'
    post 'system_config/update' => 'system_configs#update'
  end

  root 'requests/clonings#index'

end

app/views/layouts/_admin_menu.html.haml
#tbl-menu
  .col-1
    &nbsp
  .col-2
    %ul#admin-menu
      %li
        %a Catálogos
        %ul
          %li
            - if controller_name == 'clonings'
              =label_tag t('titles.requests_clonings'), nil, class: 'ui-state-disabled'
            - else
              =link_to t('titles.requests_clonings'), requests_clonings_path
          %li
            - if controller_name == 'users'
              =label_tag t('titles.users'), nil, class: 'ui-state-disabled'
            - else
              =link_to t('titles.users'), admin_users_path
          %li
            - if controller_name == 'system_configs'
              =label_tag t('titles.system_config'), nil, class: 'ui-state-disabled'
            - else
              =link_to t('titles.system_config'), admin_system_config_path
          %li
            =link_to t('commands.sign_out'), destroy_devise_user_session_path, method: :delete

app/views/layouts/_alert_notice.html.haml
- if flash[:notice]
  .ui-state-highlight.ui-corner-all
    .icon.ui-icon.ui-icon-info
    .message
      = notice
  .sp

- if flash[:alert]
  .ui-state-error.ui-corner-all
    .icon.ui-icon.ui-icon-alert
    .message
      = alert
  .sp

- flash[:alert], flash[:notice] = nil

app/views/layouts/_delete_dialog.html.haml
-#Translate messages
.icon.ui-icon.ui-icon-alert
.message
  Este registro será eliminado de forma permanente.
  %br
  ¿Está seguro?"
.sp
.t-right
  -# You should pass parameter "record"
  =link_to 'Aceptar', record, :method => :delete, :remote => true, :class => 'fa fa-btn fa-border'
  =link_to_function 'Cancelar', "$('#delete-dialog').dialog('close');", :class => 'fa fa-btn fa-border'

app/views/layouts/_search.html.haml
= simple_form_for url, method: :get, remote: true do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  .tbl-search
    .col-1
      = text_field_tag :search, '', :size => 23
    .col-2.t-cent
      = submit_tag_fa_button t('commands.search')
      = link_to_fa_button({url: url, text: t('commands.list_all'), icon: ''})

app/views/layouts/_validation_errors.html.haml
-if errors.try(:any?)
  .error-explanation
    .ui-state-error.ui-corner-all
      .icon.ui-icon.ui-icon-alert
      .message
        = "#{errors.count} error(es) impiden guardar este registro."
      %ul
        - errors.full_messages.each do |msg|
          %li
            = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Solicitud de Clonación de Productos de PCR
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %body
      #container
        #header
        .sp
        #content
          = yield
      #footer
        Intituto de Neurobiología UNAM | Ramón Martínez Olvera